version: '3.9'
services:
  bot:
    image: ghcr.io/tsi-unito/UnitoBOT
    restart: unless-stopped
    volumes:
      - ./api_key:/usr/src/app/api_key
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
